kill @e[tag=craftingSBF]
kill @e[tag=craftingSIFF]

execute as @a[tag=playF,nbt={SelectedItem:{id:"minecraft:crafting_table",tag:{Crafting:1b}}}] at @s anchored eyes positioned ^ ^ ^3 align xyz run summon falling_block ~0.5 ~ ~0.5 {BlockState:{Name:"minecraft:brown_stained_glass"},NoGravity:1b,HasVisualFire:0b,Time:1,Tags:["craftingSBF"]}
execute as @a[tag=playF,nbt={SelectedItem:{id:"minecraft:crafting_table",tag:{Crafting:1b}}},y_rotation=135.1..-135] at @s anchored eyes positioned ^ ^ ^3 run summon item_frame ~ ~1 ~ {NoGravity:1b,Facing:1b,Fixed:1b,ItemRotation:3b,Invulnerable:1b,Invisible:1b,Tags:["craftingSIFF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,nbt={SelectedItem:{id:"minecraft:crafting_table",tag:{Crafting:1b}}},y_rotation=-134.9..-45.1] at @s anchored eyes positioned ^ ^ ^3 run summon item_frame ~ ~1 ~ {NoGravity:1b,Facing:1b,Fixed:1b,ItemRotation:5b,Invulnerable:1b,Invisible:1b,Tags:["craftingSIFF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,nbt={SelectedItem:{id:"minecraft:crafting_table",tag:{Crafting:1b}}},y_rotation=-45.1..45] at @s anchored eyes positioned ^ ^ ^3 run summon item_frame ~ ~1 ~ {NoGravity:1b,Facing:1b,Fixed:1b,ItemRotation:7b,Invulnerable:1b,Invisible:1b,Tags:["craftingSIFF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,nbt={SelectedItem:{id:"minecraft:crafting_table",tag:{Crafting:1b}}},y_rotation=45.1..135] at @s anchored eyes positioned ^ ^ ^3 run summon item_frame ~ ~1 ~ {NoGravity:1b,Facing:1b,Fixed:1b,ItemRotation:1b,Invulnerable:1b,Invisible:1b,Tags:["craftingSIFF"],Item:{id:"minecraft:oak_stairs",Count:1b}}

execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]}] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air run tag @s add completeCTF
execute as @a[tag=playF,y_rotation=45.1..135,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run summon item_frame ~ ~1 ~ {Invulnerable:1b,Facing:1b,ItemRotation:1b,Invisible:1b,Tags:["craftingF","arrowF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,y_rotation=135.1..-135,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run summon item_frame ~ ~1 ~ {Invulnerable:1b,Facing:1b,ItemRotation:3b,Invisible:1b,Tags:["craftingF","arrowF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,y_rotation=-134.9..-45.1,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run summon item_frame ~ ~1 ~ {Invulnerable:1b,Facing:1b,ItemRotation:5b,Invisible:1b,Tags:["craftingF","arrowF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,y_rotation=-45.1..45,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run summon item_frame ~ ~1 ~ {Invulnerable:1b,Facing:1b,ItemRotation:7b,Invisible:1b,Tags:["craftingF","arrowF"],Item:{id:"minecraft:oak_stairs",Count:1b}}
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run playsound minecraft:block.smithing_table.use master @s ~ ~ ~ 100 1 1
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air align xyz run particle minecraft:block minecraft:crafting_table ~0.5 ~0.5 ~0.5 0.3 0.3 0.3 0 50 normal @a
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ air unless block ~ ~-1 ~ air run setblock ~ ~ ~ crafting_table keep
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ minecraft:crafting_table unless block ~ ~-1 ~ air run clear @s minecraft:crafting_table{Crafting:1b} 1
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]},tag=completeCTF] at @s anchored eyes positioned ^ ^ ^3 if block ~ ~ ~ minecraft:crafting_table unless block ~ ~-1 ~ air run tag @s remove completeCTF
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]}] at @s anchored eyes positioned ^ ^ ^3 unless block ~ ~-1 ~ air store result score @s craftingIUF run data get entity @s Inventory[{Slot:-106b}].Count
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]}] at @s anchored eyes positioned ^ ^ ^3 unless block ~ ~-1 ~ air run summon minecraft:item ^ ^-1 ^-3 {Tags:["craftingSIF"],PickupDelay:0,Item:{id:"minecraft:crafting_table",Count:1b,tag:{Crafting:1b,display:{Name:'{"text":"제조대","color":"#9d8d51","bold":false,"italic":false}'}}}}
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]}] at @s anchored eyes positioned ^ ^ ^3 unless block ~ ~-1 ~ air store result entity @e[tag=craftingSIF,limit=1,sort=nearest] Item.Count int 1 run scoreboard players get @s craftingIUF
execute as @a[tag=playF,nbt={Inventory:[{id:"minecraft:crafting_table",Slot:-106b,tag:{Crafting:1b}}]}] at @s anchored eyes positioned ^ ^ ^3 unless block ~ ~-1 ~ air unless block ~ ~ ~ air run item replace entity @s weapon.offhand with air 1

execute as @e[tag=craftingRIF] at @s run give @s crafting_table{Crafting:1b,display:{Name:'{"text":"제조대","color":"#9d8d51","bold":false,"italic":false}'}} 1
execute as @e[tag=craftingRIF] at @s run tag @s remove craftingRIF

execute as @e[tag=itemF] at @s if entity @e[tag=craftingF,nbt={ItemRotation:1b},distance=0..1.05] run scoreboard players set @s rotationF 1
execute as @e[tag=itemF] at @s if entity @e[tag=craftingF,nbt={ItemRotation:3b},distance=0..1.05] run scoreboard players set @s rotationF 2
execute as @e[tag=itemF] at @s if entity @e[tag=craftingF,nbt={ItemRotation:5b},distance=0..1.05] run scoreboard players set @s rotationF 3
execute as @e[tag=itemF] at @s if entity @e[tag=craftingF,nbt={ItemRotation:7b},distance=0..1.05] run scoreboard players set @s rotationF 4